[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nudl-py"
version = "0.1.0"
description = "A python media downloader"
authors = [{ name = "erujs" }]
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"

dependencies = [
    "yt-dlp",
    "gallery-dl",
]

[project.scripts]
nudl-py = "nudl.main:main"
nudl-login = "nudl.auth.manager:login_main"

[tool.setuptools]
packages = ["nudl", "nudl.auth"]
